/**
 * BibcodeQueryLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Servers = {

    /**
     * TODO: Write general description for this element
     */
    BIBCODE_QUERY_PORT: 'BibcodeQueryPort',

};

module.exports = Servers;
